name: simple_3d
description: Simple 3D Format for Dart.
version: 0.0.1
repository: https://github.com/MasahideMori1111/simple_3d

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter